// <auto-generated />
using System;
using GoldenBurger.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenBurger.DAL.Migrations
{
    [DbContext(typeof(GoldenBurgerContext))]
    [Migration("20240318060505_inidb100")]
    partial class inidb100
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoldenBurger.Concrete.Basket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SepetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5459),
                            Price = 0.0,
                            SepetAdi = "ilkSepet",
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Burgers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1286),
                            MenuId = 1,
                            Name = "Big King Jr.",
                            PhotoPath = "MenusPictures\\big-king-jr-menu.png",
                            Price = 189.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1299),
                            MenuId = 2,
                            Name = "SteakHouse Burger",
                            PhotoPath = "MenusPictures\\bk-steakhouse-burger-menu.png",
                            Price = 169.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1302),
                            MenuId = 3,
                            Name = "Cheese Burger",
                            PhotoPath = "MenusPictures\\cheeseburger-menu.png",
                            Price = 145.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1304),
                            MenuId = 4,
                            Name = "Double Big King",
                            PhotoPath = "MenusPictures\\double-big-king-menu.png",
                            Price = 120.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1307),
                            MenuId = 5,
                            Name = "Double Cheeseburger",
                            PhotoPath = "MenusPictures\\double-cheeseburger-menu.png",
                            Price = 109.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1311),
                            MenuId = 6,
                            Name = "Double King Chicken",
                            PhotoPath = "MenusPictures\\double-king-chicken-menu.png",
                            Price = 119.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1313),
                            MenuId = 7,
                            Name = "Double Köfte Burger",
                            PhotoPath = "MenusPictures\\double-kofteburger-menu.png",
                            Price = 129.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1316),
                            MenuId = 8,
                            Name = "Double Whopper Jr.",
                            PhotoPath = "MenusPictures\\double-whopper-jr-menu.png",
                            Price = 135.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1319),
                            MenuId = 9,
                            Name = "Double Whopper",
                            PhotoPath = "MenusPictures\\double-whopper-menu.png",
                            Price = 155.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1323),
                            MenuId = 10,
                            Name = "Etli Barbekü Deluxe Burger",
                            PhotoPath = "MenusPictures\\etli-barbeku-deluxe-burger-menu.png",
                            Price = 169.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1325),
                            MenuId = 11,
                            Name = "King Beef Burger",
                            PhotoPath = "MenusPictures\\king-beef-burger-menu.png",
                            Price = 159.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1327),
                            MenuId = 12,
                            Name = "King Chicken",
                            PhotoPath = "MenusPictures\\king-chicken-menu.png",
                            Price = 99.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1330),
                            MenuId = 13,
                            Name = "Köfte Burger",
                            PhotoPath = "MenusPictures\\kofteburger-menu.png",
                            Price = 119.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1332),
                            MenuId = 14,
                            Name = "Mega Double Cheeseburger",
                            PhotoPath = "MenusPictures\\mega-double-cheeseburger-menu.png",
                            Price = 149.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1334),
                            MenuId = 15,
                            Name = "Plant Based Whopper",
                            PhotoPath = "MenusPictures\\plant-based-whopper-menu.png",
                            Price = 129.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1337),
                            MenuId = 16,
                            Name = "Rodeo Whopper",
                            PhotoPath = "MenusPictures\\rodeo-whopper-menu.png",
                            Price = 134.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1339),
                            MenuId = 17,
                            Name = "Tavuklu Barbekü Brioche",
                            PhotoPath = "MenusPictures\\tavuklu-barbeku-brioche-menu.png",
                            Price = 115.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1342),
                            MenuId = 18,
                            Name = "Texas SmokeHouse Burger",
                            PhotoPath = "MenusPictures\\texas-smokehouse-burger-menu.png",
                            Price = 150.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1345),
                            MenuId = 19,
                            Name = "Triple Whopper",
                            PhotoPath = "MenusPictures\\triple-whopper-menu.png",
                            Price = 145.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1347),
                            MenuId = 20,
                            Name = "Trüflü King Beef Burger",
                            PhotoPath = "MenusPictures\\truflu-king-beef-burger-menu.png",
                            Price = 135.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1349),
                            MenuId = 21,
                            Name = "Whopper Jr.",
                            PhotoPath = "MenusPictures\\whopper-jr-menu.png",
                            Price = 99.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 129, DateTimeKind.Local).AddTicks(1352),
                            MenuId = 22,
                            Name = "Whopper",
                            PhotoPath = "MenusPictures\\whopper-menu.png",
                            Price = 100.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Chips", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("ChipsType")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Chips");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            ChipsType = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8696),
                            MenuId = 1,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\tirtikli-patates.png",
                            Price = 34.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8711),
                            MenuId = 2,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 32.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8713),
                            MenuId = 3,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8716),
                            MenuId = 4,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8718),
                            MenuId = 5,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8722),
                            MenuId = 6,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8725),
                            MenuId = 7,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8727),
                            MenuId = 8,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8729),
                            MenuId = 9,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8774),
                            MenuId = 10,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8778),
                            MenuId = 11,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8780),
                            MenuId = 12,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8782),
                            MenuId = 13,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8785),
                            MenuId = 14,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8787),
                            MenuId = 15,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8789),
                            MenuId = 16,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8791),
                            MenuId = 17,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8794),
                            MenuId = 18,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8796),
                            MenuId = 19,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8798),
                            MenuId = 20,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8800),
                            MenuId = 21,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 119, DateTimeKind.Local).AddTicks(8802),
                            MenuId = 22,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Drink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9532),
                            MenuId = 1,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9546),
                            MenuId = 2,
                            Name = "Coca Cola Light",
                            PhotoPath = "MenusPictures\\coca-cola-light.png",
                            Price = 23.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9549),
                            MenuId = 3,
                            Name = "Coca Cola Zero Sugar",
                            PhotoPath = "MenusPictures\\coca-cola-zero-sugar.png",
                            Price = 23.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9552),
                            MenuId = 4,
                            Name = "Fuse Tea",
                            PhotoPath = "MenusPictures\\fuse-tea.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9554),
                            MenuId = 5,
                            Name = "Fanta",
                            PhotoPath = "MenusPictures\\fanta.png",
                            Price = 22.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9558),
                            MenuId = 6,
                            Name = "Sprite",
                            PhotoPath = "MenusPictures\\sprite.png",
                            Price = 24.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9560),
                            MenuId = 7,
                            Name = "Ayran 300 ml",
                            PhotoPath = "MenusPictures\\ayran-300-ml.png",
                            Price = 30.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9562),
                            MenuId = 8,
                            Name = "Ayran 195 ml",
                            PhotoPath = "MenusPictures\\ayran-195-ml.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9564),
                            MenuId = 9,
                            Name = "Elma Suyu",
                            PhotoPath = "MenusPictures\\elma-suyu.png",
                            Price = 16.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9568),
                            MenuId = 10,
                            Name = "Cappy Atom",
                            PhotoPath = "MenusPictures\\cappy-atom-200-ml.png",
                            Price = 18.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9570),
                            MenuId = 11,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9572),
                            MenuId = 12,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9575),
                            MenuId = 13,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9577),
                            MenuId = 14,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9579),
                            MenuId = 15,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9581),
                            MenuId = 16,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9583),
                            MenuId = 17,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9586),
                            MenuId = 18,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9588),
                            MenuId = 19,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9590),
                            MenuId = 20,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9592),
                            MenuId = 21,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 122, DateTimeKind.Local).AddTicks(9651),
                            MenuId = 22,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("BurgerId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("BurgerId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7242),
                            Name = "Turşu",
                            Price = 5.5,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            BurgerId = 2,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7258),
                            Name = "Domates",
                            Price = 7.5,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            BurgerId = 3,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7261),
                            Name = "Ketçap",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7263),
                            Name = "Mayonez",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7265),
                            Name = "Hardal",
                            Price = 10.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 128, DateTimeKind.Local).AddTicks(7269),
                            Name = "Marul",
                            Price = 12.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8445),
                            Name = "Big King Jr. Menü",
                            PhotoPath = "MenusPictures\\big-king-jr-menu.png",
                            Price = 219.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8487),
                            Name = "SteakHouse Burger Menü",
                            PhotoPath = "MenusPictures\\bk-steakhouse-burger-menu.png",
                            Price = 229.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8490),
                            Name = "Cheese Burger Menü",
                            PhotoPath = "MenusPictures\\cheeseburger-menu.png",
                            Price = 200.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8492),
                            Name = "Double Big King Menü",
                            PhotoPath = "MenusPictures\\double-big-king-menu.png",
                            Price = 240.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8495),
                            Name = "Double Cheeseburger Menü",
                            PhotoPath = "MenusPictures\\double-cheeseburger-menu.png",
                            Price = 235.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8499),
                            Name = "Double King Chicken Menü",
                            PhotoPath = "MenusPictures\\double-king-chicken-menu.png",
                            Price = 199.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8501),
                            Name = "Double Köfte Burger Menü",
                            PhotoPath = "MenusPictures\\double-kofteburger-menu.png",
                            Price = 235.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8503),
                            Name = "Double Whopper Jr. Menü",
                            PhotoPath = "MenusPictures\\double-whopper-jr-menu.png",
                            Price = 249.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8505),
                            Name = "Double Whopper Menü",
                            PhotoPath = "MenusPictures\\double-whopper-menu.png",
                            Price = 219.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8508),
                            Name = "Etli Barbekü Deluxe Burger Menü",
                            PhotoPath = "MenusPictures\\etli-barbeku-deluxe-burger-menu.png",
                            Price = 269.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8510),
                            Name = "King Beef Burger Menü",
                            PhotoPath = "MenusPictures\\king-beef-burger-menu.png",
                            Price = 280.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8514),
                            Name = "King Chicken Menü",
                            PhotoPath = "MenusPictures\\king-chicken-menu.png",
                            Price = 209.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8516),
                            Name = "Köfte Burger Menü",
                            PhotoPath = "MenusPictures\\kofteburger-menu.png",
                            Price = 216.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8518),
                            Name = "Mega Double Cheeseburger Menü",
                            PhotoPath = "MenusPictures\\mega-double-cheeseburger-menu.png",
                            Price = 230.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8520),
                            Name = "Plant Based Whopper Menü",
                            PhotoPath = "MenusPictures\\plant-based-whopper-menu.png",
                            Price = 250.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8522),
                            Name = "Rodeo Whopper Menü",
                            PhotoPath = "MenusPictures\\rodeo-whopper-menu.png",
                            Price = 269.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8524),
                            Name = "Tavuklu Barbekü Brioche Menü",
                            PhotoPath = "MenusPictures\\tavuklu-barbeku-brioche-menu.png",
                            Price = 215.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8527),
                            Name = "Texas SmokeHouse Burger Menü",
                            PhotoPath = "MenusPictures\\texas-smokehouse-burger-menu.png",
                            Price = 255.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8529),
                            Name = "Triple Whopper Menü",
                            PhotoPath = "MenusPictures\\triple-whopper-menu.png",
                            Price = 299.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8531),
                            Name = "Trüflü King Beef Burger Menü",
                            PhotoPath = "MenusPictures\\truflu-king-beef-burger-menu.png",
                            Price = 310.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8533),
                            Name = "Whopper Jr. Menü",
                            PhotoPath = "MenusPictures\\whopper-jr-menu.png",
                            Price = 268.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 113, DateTimeKind.Local).AddTicks(8535),
                            Name = "Whopper Menü",
                            PhotoPath = "MenusPictures\\whopper-menu.png",
                            Price = 236.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.DATA.Concrete.Extra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraProductName")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5272),
                            ExtraProductName = 3,
                            Name = "Çikolatalı Cookie",
                            PhotoPath = "MenusPictures\\cikolatali-cookie.png",
                            Price = 18.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5296),
                            ExtraProductName = 3,
                            Name = "Sufle",
                            PhotoPath = "MenusPictures\\sufle.png",
                            Price = 22.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5300),
                            ExtraProductName = 3,
                            Name = "Vişneli Tatlı",
                            PhotoPath = "MenusPictures\\visneli-tatli.png",
                            Price = 28.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5302),
                            ExtraProductName = 3,
                            Name = "Elmalı Tatlı",
                            PhotoPath = "MenusPictures\\elmali-tatli.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5304),
                            ExtraProductName = 3,
                            Name = "Mini Sundea",
                            PhotoPath = "MenusPictures\\mini-sundae.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5308),
                            ExtraProductName = 6,
                            Name = "Mini Acı Sos",
                            PhotoPath = "MenusPictures\\mini-aci-sos.png",
                            Price = 8.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5310),
                            ExtraProductName = 6,
                            Name = "Mini Ranch",
                            PhotoPath = "MenusPictures\\mini-ranch.png",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5313),
                            ExtraProductName = 6,
                            Name = "Mini Ketçap",
                            PhotoPath = "MenusPictures\\mini-ketcap.png",
                            Price = 5.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5315),
                            ExtraProductName = 6,
                            Name = "Mini Mayonez",
                            PhotoPath = "MenusPictures\\mini-mayonez.png",
                            Price = 5.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5318),
                            ExtraProductName = 6,
                            Name = "Mini Bbq",
                            PhotoPath = "MenusPictures\\mini-bbq.png",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5320),
                            ExtraProductName = 6,
                            Name = "Mini Ballı Hardal",
                            PhotoPath = "MenusPictures\\mini-balli-hardal-1.png",
                            Price = 9.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 9, 5, 4, 116, DateTimeKind.Local).AddTicks(5322),
                            ExtraProductName = 6,
                            Name = "Mini Buffalo",
                            PhotoPath = "MenusPictures\\mini-buffalo-1.png",
                            Price = 8.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adminRoleId",
                            ConcurrencyStamp = "f9f94258-4ff8-4498-b07a-d3bf0de34108",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "userRoleId",
                            ConcurrencyStamp = "5ac86957-f79d-4d95-9456-bd233f8a2a9b",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adminUserId",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "38ab9198-c387-49a9-9960-7ff9dbafe389",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHnRSm7wwu5jyAOeXP8kFnecog9FysHpDYwO5c732o4JVKNvMQH4lVy9kijBH/o8zA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "adminUserId",
                            RoleId = "adminRoleId"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("burgers")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Burger")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Chips", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("chips")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Chips")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Drink", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("drinks")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Drink")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Ingredient", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("Ingredients")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Burger", "Burger")
                        .WithMany("Ingredients")
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Burger");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("menus")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("GoldenBurger.DATA.Concrete.Extra", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("extras")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Basket", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("burgers");

                    b.Navigation("chips");

                    b.Navigation("drinks");

                    b.Navigation("extras");

                    b.Navigation("menus");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.Navigation("Burger");

                    b.Navigation("Chips");

                    b.Navigation("Drink");
                });
#pragma warning restore 612, 618
        }
    }
}
