// <auto-generated />
using System;
using GoldenBurger.DAL.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenBurger.DAL.Migrations
{
    [DbContext(typeof(GoldenBurgerContext))]
    [Migration("20240317212905_initdb55")]
    partial class initdb55
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GoldenBurger.Concrete.Basket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("SepetAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Baskets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2484),
                            Price = 0.0,
                            SepetAdi = "ilkSepet",
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Burgers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7877),
                            MenuId = 1,
                            Name = "Big King Jr.",
                            PhotoPath = "MenusPictures\\big-king-jr-menu.png",
                            Price = 189.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7892),
                            MenuId = 2,
                            Name = "SteakHouse Burger",
                            PhotoPath = "MenusPictures\\bk-steakhouse-burger-menu.png",
                            Price = 169.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7895),
                            MenuId = 3,
                            Name = "Cheese Burger",
                            PhotoPath = "MenusPictures\\cheeseburger-menu.png",
                            Price = 145.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7898),
                            MenuId = 4,
                            Name = "Double Big King",
                            PhotoPath = "MenusPictures\\double-big-king-menu.png",
                            Price = 120.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7900),
                            MenuId = 5,
                            Name = "Double Cheeseburger",
                            PhotoPath = "MenusPictures\\double-cheeseburger-menu.png",
                            Price = 109.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7905),
                            MenuId = 6,
                            Name = "Double King Chicken",
                            PhotoPath = "MenusPictures\\double-king-chicken-menu.png",
                            Price = 119.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7908),
                            MenuId = 7,
                            Name = "Double Köfte Burger",
                            PhotoPath = "MenusPictures\\double-kofteburger-menu.png",
                            Price = 129.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7910),
                            MenuId = 8,
                            Name = "Double Whopper Jr.",
                            PhotoPath = "MenusPictures\\double-whopper-jr-menu.png",
                            Price = 135.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7913),
                            MenuId = 9,
                            Name = "Double Whopper",
                            PhotoPath = "MenusPictures\\double-whopper-menu.png",
                            Price = 155.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7916),
                            MenuId = 10,
                            Name = "Etli Barbekü Deluxe Burger",
                            PhotoPath = "MenusPictures\\etli-barbeku-deluxe-burger-menu.png",
                            Price = 169.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7918),
                            MenuId = 11,
                            Name = "King Beef Burger",
                            PhotoPath = "MenusPictures\\king-beef-burger-menu.png",
                            Price = 159.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7921),
                            MenuId = 12,
                            Name = "King Chicken",
                            PhotoPath = "MenusPictures\\king-chicken-menu.png",
                            Price = 99.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7923),
                            MenuId = 13,
                            Name = "Köfte Burger",
                            PhotoPath = "MenusPictures\\kofteburger-menu.png",
                            Price = 119.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7926),
                            MenuId = 14,
                            Name = "Mega Double Cheeseburger",
                            PhotoPath = "MenusPictures\\mega-double-cheeseburger-menu.png",
                            Price = 149.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7928),
                            MenuId = 15,
                            Name = "Plant Based Whopper",
                            PhotoPath = "MenusPictures\\plant-based-whopper-menu.png",
                            Price = 129.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7932),
                            MenuId = 16,
                            Name = "Rodeo Whopper",
                            PhotoPath = "MenusPictures\\rodeo-whopper-menu.png",
                            Price = 134.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7934),
                            MenuId = 17,
                            Name = "Tavuklu Barbekü Brioche",
                            PhotoPath = "MenusPictures\\tavuklu-barbeku-brioche-menu.png",
                            Price = 115.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7938),
                            MenuId = 18,
                            Name = "Texas SmokeHouse Burger",
                            PhotoPath = "MenusPictures\\texas-smokehouse-burger-menu.png",
                            Price = 150.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7941),
                            MenuId = 19,
                            Name = "Triple Whopper",
                            PhotoPath = "MenusPictures\\triple-whopper-menu.png",
                            Price = 145.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7943),
                            MenuId = 20,
                            Name = "Trüflü King Beef Burger",
                            PhotoPath = "MenusPictures\\truflu-king-beef-burger-menu.png",
                            Price = 135.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7945),
                            MenuId = 21,
                            Name = "Whopper Jr.",
                            PhotoPath = "MenusPictures\\whopper-jr-menu.png",
                            Price = 99.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(7948),
                            MenuId = 22,
                            Name = "Whopper",
                            PhotoPath = "MenusPictures\\whopper-menu.png",
                            Price = 100.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Chips", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("ChipsType")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Chips");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            ChipsType = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2554),
                            MenuId = 1,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\tirtikli-patates.png",
                            Price = 34.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2578),
                            MenuId = 2,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 32.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2582),
                            MenuId = 3,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2585),
                            MenuId = 4,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2587),
                            MenuId = 5,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2591),
                            MenuId = 6,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2593),
                            MenuId = 7,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2595),
                            MenuId = 8,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2597),
                            MenuId = 9,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2663),
                            MenuId = 10,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2666),
                            MenuId = 11,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2669),
                            MenuId = 12,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2671),
                            MenuId = 13,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2673),
                            MenuId = 14,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2676),
                            MenuId = 15,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2678),
                            MenuId = 16,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2680),
                            MenuId = 17,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2684),
                            MenuId = 18,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2687),
                            MenuId = 19,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2689),
                            MenuId = 20,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2691),
                            MenuId = 21,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            ChipsType = 0,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 731, DateTimeKind.Local).AddTicks(2694),
                            MenuId = 22,
                            Name = "Patates",
                            PhotoPath = "MenusPictures\\patates.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Drink", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("MenuId");

                    b.ToTable("Drinks");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6405),
                            MenuId = 1,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6428),
                            MenuId = 2,
                            Name = "Coca Cola Light",
                            PhotoPath = "MenusPictures\\coca-cola-light.png",
                            Price = 23.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6431),
                            MenuId = 3,
                            Name = "Coca Cola Zero Sugar",
                            PhotoPath = "MenusPictures\\coca-cola-zero-sugar.png",
                            Price = 23.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6433),
                            MenuId = 4,
                            Name = "Fuse Tea",
                            PhotoPath = "MenusPictures\\fuse-tea.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6435),
                            MenuId = 5,
                            Name = "Fanta",
                            PhotoPath = "MenusPictures\\fanta.png",
                            Price = 22.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6439),
                            MenuId = 6,
                            Name = "Sprite",
                            PhotoPath = "MenusPictures\\sprite.png",
                            Price = 24.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6441),
                            MenuId = 7,
                            Name = "Ayran 300 ml",
                            PhotoPath = "MenusPictures\\ayran-300-ml.png",
                            Price = 30.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6444),
                            MenuId = 8,
                            Name = "Ayran 195 ml",
                            PhotoPath = "MenusPictures\\ayran-195-ml.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6446),
                            MenuId = 9,
                            Name = "Elma Suyu",
                            PhotoPath = "MenusPictures\\elma-suyu.png",
                            Price = 16.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6450),
                            MenuId = 10,
                            Name = "Cappy Atom",
                            PhotoPath = "MenusPictures\\cappy-atom-200-ml.png",
                            Price = 18.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6452),
                            MenuId = 11,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6454),
                            MenuId = 12,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6456),
                            MenuId = 13,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6458),
                            MenuId = 14,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6460),
                            MenuId = 15,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6462),
                            MenuId = 16,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6465),
                            MenuId = 17,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6467),
                            MenuId = 18,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6470),
                            MenuId = 19,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6473),
                            MenuId = 20,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6475),
                            MenuId = 21,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 734, DateTimeKind.Local).AddTicks(6521),
                            MenuId = 22,
                            Name = "Coca Cola",
                            PhotoPath = "MenusPictures\\coca-cola.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = false
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Ingredient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("BurgerId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.HasIndex("BurgerId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(3987),
                            Name = "Turşu",
                            Price = 5.5,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            BurgerId = 2,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(4005),
                            Name = "Domates",
                            Price = 7.5,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            BurgerId = 3,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(4009),
                            Name = "Ketçap",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(4011),
                            Name = "Mayonez",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(4013),
                            Name = "Hardal",
                            Price = 10.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            BurgerId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 740, DateTimeKind.Local).AddTicks(4017),
                            Name = "Marul",
                            Price = 12.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(156),
                            Name = "Big King Jr. Menü",
                            PhotoPath = "MenusPictures\\big-king-jr-menu.png",
                            Price = 219.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(184),
                            Name = "SteakHouse Burger Menü",
                            PhotoPath = "MenusPictures\\bk-steakhouse-burger-menu.png",
                            Price = 229.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(187),
                            Name = "Cheese Burger Menü",
                            PhotoPath = "MenusPictures\\cheeseburger-menu.png",
                            Price = 200.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(189),
                            Name = "Double Big King Menü",
                            PhotoPath = "MenusPictures\\double-big-king-menu.png",
                            Price = 240.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(191),
                            Name = "Double Cheeseburger Menü",
                            PhotoPath = "MenusPictures\\double-cheeseburger-menu.png",
                            Price = 235.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(195),
                            Name = "Double King Chicken Menü",
                            PhotoPath = "MenusPictures\\double-king-chicken-menu.png",
                            Price = 199.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(198),
                            Name = "Double Köfte Burger Menü",
                            PhotoPath = "MenusPictures\\double-kofteburger-menu.png",
                            Price = 235.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(200),
                            Name = "Double Whopper Jr. Menü",
                            PhotoPath = "MenusPictures\\double-whopper-jr-menu.png",
                            Price = 249.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(202),
                            Name = "Double Whopper Menü",
                            PhotoPath = "MenusPictures\\double-whopper-menu.png",
                            Price = 219.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(205),
                            Name = "Etli Barbekü Deluxe Burger Menü",
                            PhotoPath = "MenusPictures\\etli-barbeku-deluxe-burger-menu.png",
                            Price = 269.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(207),
                            Name = "King Beef Burger Menü",
                            PhotoPath = "MenusPictures\\king-beef-burger-menu.png",
                            Price = 280.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(209),
                            Name = "King Chicken Menü",
                            PhotoPath = "MenusPictures\\king-chicken-menu.png",
                            Price = 209.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 13,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(211),
                            Name = "Köfte Burger Menü",
                            PhotoPath = "MenusPictures\\kofteburger-menu.png",
                            Price = 216.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 14,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(213),
                            Name = "Mega Double Cheeseburger Menü",
                            PhotoPath = "MenusPictures\\mega-double-cheeseburger-menu.png",
                            Price = 230.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 15,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(215),
                            Name = "Plant Based Whopper Menü",
                            PhotoPath = "MenusPictures\\plant-based-whopper-menu.png",
                            Price = 250.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 16,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(218),
                            Name = "Rodeo Whopper Menü",
                            PhotoPath = "MenusPictures\\rodeo-whopper-menu.png",
                            Price = 269.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 17,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(220),
                            Name = "Tavuklu Barbekü Brioche Menü",
                            PhotoPath = "MenusPictures\\tavuklu-barbeku-brioche-menu.png",
                            Price = 215.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 18,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(223),
                            Name = "Texas SmokeHouse Burger Menü",
                            PhotoPath = "MenusPictures\\texas-smokehouse-burger-menu.png",
                            Price = 255.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 19,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(224),
                            Name = "Triple Whopper Menü",
                            PhotoPath = "MenusPictures\\triple-whopper-menu.png",
                            Price = 299.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 20,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(227),
                            Name = "Trüflü King Beef Burger Menü",
                            PhotoPath = "MenusPictures\\truflu-king-beef-burger-menu.png",
                            Price = 310.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 21,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(229),
                            Name = "Whopper Jr. Menü",
                            PhotoPath = "MenusPictures\\whopper-jr-menu.png",
                            Price = 268.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 22,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 725, DateTimeKind.Local).AddTicks(294),
                            Name = "Whopper Menü",
                            PhotoPath = "MenusPictures\\whopper-menu.png",
                            Price = 236.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("GoldenBurger.DATA.Concrete.Extra", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("BasketId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtraProductName")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("BasketId");

                    b.ToTable("Extras");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2317),
                            ExtraProductName = 3,
                            Name = "Çikolatalı Cookie",
                            PhotoPath = "MenusPictures\\cikolatali-cookie.png",
                            Price = 18.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 2,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2335),
                            ExtraProductName = 3,
                            Name = "Sufle",
                            PhotoPath = "MenusPictures\\sufle.png",
                            Price = 22.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 3,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2340),
                            ExtraProductName = 3,
                            Name = "Vişneli Tatlı",
                            PhotoPath = "MenusPictures\\visneli-tatli.png",
                            Price = 28.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 4,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2342),
                            ExtraProductName = 3,
                            Name = "Elmalı Tatlı",
                            PhotoPath = "MenusPictures\\elmali-tatli.png",
                            Price = 25.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 5,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2345),
                            ExtraProductName = 3,
                            Name = "Mini Sundea",
                            PhotoPath = "MenusPictures\\mini-sundae.png",
                            Price = 20.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 6,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2349),
                            ExtraProductName = 6,
                            Name = "Mini Acı Sos",
                            PhotoPath = "MenusPictures\\mini-aci-sos.png",
                            Price = 8.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 7,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2352),
                            ExtraProductName = 6,
                            Name = "Mini Ranch",
                            PhotoPath = "MenusPictures\\mini-ranch.png",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 8,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2354),
                            ExtraProductName = 6,
                            Name = "Mini Ketçap",
                            PhotoPath = "MenusPictures\\mini-ketcap.png",
                            Price = 5.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 9,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2356),
                            ExtraProductName = 6,
                            Name = "Mini Mayonez",
                            PhotoPath = "MenusPictures\\mini-mayonez.png",
                            Price = 5.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 10,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2359),
                            ExtraProductName = 6,
                            Name = "Mini Bbq",
                            PhotoPath = "MenusPictures\\mini-bbq.png",
                            Price = 6.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 11,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2361),
                            ExtraProductName = 6,
                            Name = "Mini Ballı Hardal",
                            PhotoPath = "MenusPictures\\mini-balli-hardal-1.png",
                            Price = 9.0,
                            Status = 0,
                            Visible = true
                        },
                        new
                        {
                            ID = 12,
                            BasketId = 1,
                            Count = 0,
                            CreatedDate = new DateTime(2024, 3, 18, 0, 29, 4, 727, DateTimeKind.Local).AddTicks(2363),
                            ExtraProductName = 6,
                            Name = "Mini Buffalo",
                            PhotoPath = "MenusPictures\\mini-buffalo-1.png",
                            Price = 8.0,
                            Status = 0,
                            Visible = true
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adminRoleId",
                            ConcurrencyStamp = "cb1c3423-4d23-448e-96f6-923acf75032b",
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "userRoleId",
                            ConcurrencyStamp = "613ab6f2-4df7-4efb-8ed0-8fbb0975850a",
                            Name = "user",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "adminUserId",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "67fd970e-cb14-4961-956d-751b7d8c263a",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEM1uW5k4zG/VtNSRS7pNBtkehTETrOtWu0CMwK7zOrn2iRA6lQ32VRzNsyFt+dupHQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "adminUserId",
                            RoleId = "adminRoleId"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("burgers")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Burger")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Chips", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("chips")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Chips")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Drink", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("drinks")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Menu", "Menu")
                        .WithMany("Drink")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Ingredient", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("Ingredients")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenBurger.Concrete.Burger", "Burger")
                        .WithMany("Ingredients")
                        .HasForeignKey("BurgerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Burger");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("menus")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("GoldenBurger.DATA.Concrete.Extra", b =>
                {
                    b.HasOne("GoldenBurger.Concrete.Basket", "Basket")
                        .WithMany("extras")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Basket");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Basket", b =>
                {
                    b.Navigation("Ingredients");

                    b.Navigation("burgers");

                    b.Navigation("chips");

                    b.Navigation("drinks");

                    b.Navigation("extras");

                    b.Navigation("menus");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Burger", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("GoldenBurger.Concrete.Menu", b =>
                {
                    b.Navigation("Burger");

                    b.Navigation("Chips");

                    b.Navigation("Drink");
                });
#pragma warning restore 612, 618
        }
    }
}
